In [1]:
import numpy as np

In [ ]:
#How to create an empty and a full NumPy array?
empty_arr = np.array([])
full_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(empty_arr)
print(full_arr)

[]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Create a Numpy array filled with all zeros
arr = np.zeros([3, 3], dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#Create a Numpy array filled with all ones
arr = np.ones([3, 3], dtype = int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Check whether a Numpy array contains a specified row
arr = np.ones([3, 3], dtype = int) # 3x3 array filled with ones 
row_1 = [1, 1, 1]
row_2 = [1, 1, 0]

print(arr)
print(row_1 in arr.tolist())
print(row_2 in arr.tolist())

[[1 1 1]
 [1 1 1]
 [1 1 1]]
True
False


In [ ]:
#How to Remove rows in Numpy array that contains non-numeric values?
arr = np.array([[1, np.nan, 3], [4, np.nan, np.nan], [7, 8, 9]])
print(arr)
  
arr = arr[~np.isnan(arr).any(axis=1)]# removing rows with nan values 
print(arr)

[[ 1. nan  3.]
 [ 4. nan nan]
 [ 7.  8.  9.]]
[[7. 8. 9.]]


In [ ]:
#Remove single-dimensional entries from the shape of an array
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr.shape)
arr = arr.squeeze()
print(arr.shape)

(1, 2, 3)
(2, 3)


In [ ]:
#Find the number of occurrences of a sequence in a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 3, 2], [3, 1, 2]])
print(arr)
sequence = "1, 2"
print(repr(arr).count(sequence))

[[1 2 3]
 [4 5 6]
 [1 3 2]
 [3 1 2]]
2


In [ ]:
#Find the most frequent value in a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 1, 3, 2, 3, 1, 2])
print(arr)

element_count = np.bincount(arr)
index = 0

while index < len(element_count):
    if element_count[index] == max(element_count):
      print(index, end=" ")

    index += 1

[1 2 3 4 5 6 1 3 2 3 1 2]
1 2 3 

In [ ]:
#Combining a one and a two-dimensional NumPy Array
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

for (i, j) in np.nditer([arr_1d, arr_2d]):
  print(i, j)

1 4
2 5
3 6
1 7
2 8
3 9


In [ ]:
#How to build an array of all combinations of two NumPy arrays?
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(np.array(np.meshgrid(arr_1, arr_2)).T.reshape(-1, 2))

[[1 4]
 [1 5]
 [1 6]
 [2 4]
 [2 5]
 [2 6]
 [3 4]
 [3 5]
 [3 6]]


In [ ]:
#How to add a border around a NumPy array?
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
  
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=-1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[-1 -1 -1 -1 -1]
 [-1  1  2  3 -1]
 [-1  4  5  6 -1]
 [-1 -1 -1 -1 -1]]


In [ ]:
#How to compare two NumPy arrays?
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

comparison = (arr_1 == arr_2)

if comparison.all():
  print('Iguais')
else:
  print('Diferentes')

Diferentes


In [ ]:
#How to check whether specified values are present in NumPy array?
arr = np.array([1, 2, 3])

print(1 in arr)
print(4 in arr)

True
False


In [ ]:
#How to get all 2D diagonals of a 3D NumPy array?
arr = np.arange(3 * 3 * 3).reshape(3, 3, 3)
print(arr)  
print('--------------------------------------')

diagonals = np.diagonal(arr)
print(diagonals)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------------------------
[[ 0 12 24]
 [ 1 13 25]
 [ 2 14 26]]


In [ ]:
#Flatten a Matrix in Python using NumPy
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#Flatten a 2d numpy array into 1d array
# basically the same thing that the question above does, so I just repeated the flatten() method
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#Move axes of an array to new positions
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr.shape)

arr = np.moveaxis(arr, 0, 1)
print(arr.shape)

(2, 3)
(3, 2)


In [ ]:
#Interchange two axes of an array
#Pretty much the same thing, but the method swapaxes swap two axes while moveaxis can move the position of more than 2 axes
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr.shape)

arr = np.swapaxes(arr, 0, 1)
print(arr.shape)

(2, 3)
(3, 2)


In [ ]:
#NumPy – Fibonacci Series using Binet Formula
n = int(input("Enter the value of n: "))
fibonacci_numbers = np.arange(0, n)

alpha = (1 + np.sqrt(5)) / 2
beta = (1 - np.sqrt(5)) / 2
fn = ((alpha ** fibonacci_numbers) - (beta ** fibonacci_numbers)) * (1 / np.sqrt(5))

print("These are the numbers of the first n fibonacci series:")
print(fn)

Enter the value of n: 10
These are the numbers of the first n fibonacci series:
[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]


In [ ]:
#Counts the number of non-zero values in the array
arr = np.array([1, 2, 3, 0, 1, 2, 0, 3, 40, 0, 2])
print(np.count_nonzero(arr))

8


In [ ]:
#Count the number of elements along a given axis
arr = np.array([[1, 2, 3], [4, 5, 6]]) 

print(np.size(arr, 0)) # x-axis
print(np.size(arr, 1)) # y-axis

2
3


In [ ]:
#Trim the leading and/or trailing zeros from a 1-D array
arr = np.array([0, 0, 1, 2, 3, 0, 1, 2, 0, 3, 40, 0, 2, 0])
print(arr)

arr = np.trim_zeros(arr)
print(arr)

[ 0  0  1  2  3  0  1  2  0  3 40  0  2  0]
[ 1  2  3  0  1  2  0  3 40  0  2]


In [ ]:
#Change data type of given numpy array
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = arr.astype('bool')
print(arr.dtype)

int64
bool
[ True  True  True]


In [ ]:
#Reverse a numpy array
arr = np.array([1, 2, 3])
print(arr)

arr = np.flipud(arr)
print(arr)

[1 2 3]
[3 2 1]


In [ ]:
#How to make a NumPy array read-only?
arr = np.array([1, 2, 3])
print(arr)

arr[0] = 10
print(arr)

arr.flags.writeable = False
#arr[0] = 2 #uncomment to see the error

[1 2 3]
[10  2  3]


In [ ]:
#Get the maximum value from given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.max(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
9


In [ ]:
#Get the minimum value from given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.min(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
0


In [ ]:
#Find the number of rows and columns of a given matrix using NumPy
arr = np.arange(10).reshape(2, 5)
print(arr.shape)

(2, 5)


In [ ]:
#Select the elements from a given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(arr[0][2])
print(arr[1][1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
6


In [ ]:
#Find the sum of values in a matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.sum(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45


In [ ]:
#Calculate the sum of the diagonal elements of a NumPy array
arr = np.arange(9).reshape(3, 3)
print(arr)

diagonal_sum = np.trace(arr)
print(diagonal_sum)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [ ]:
#Adding and Subtracting Matrices in Python
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])

print(np.add(arr_1, arr_2))
print(np.subtract(arr_1, arr_2))

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
#Ways to add row/columns in numpy array
arr = np.array([1, 2, 3])
print(arr)

new_row = np.array([4, 5, 6])
arr = np.vstack((arr, new_row))
print(arr)


new_column = np.array([10, 11])
arr = np.column_stack((arr, new_column))
print(arr)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [ ]:
#Matrix Multiplication in NumPy
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(arr_1.dot(arr_2))

[[ 66  72  78]
 [156 171 186]]


In [ ]:
#Get the eigen values of a matrix
arr = np.array([[1, 2], [3, 4]])

eigen_values, eigen_vectors = np.linalg.eig(arr)
print(eigen_values)

[-0.37228132  5.37228132]


In [ ]:
#How to Calculate the determinant of a matrix using NumPy?
arr = np.array([[1, 2], [3, 4]])

determinant = int(np.linalg.det(arr))
print(determinant)

-2


In [ ]:
#How to inverse a matrix using NumPy
arr = np.array([[1, 2], [3, 4]])
print(arr)

inverse_arr = np.linalg.inv(arr)
print(inverse_arr)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#How to count the frequency of unique values in NumPy array?
arr = np.array([1, 2, 3, 1, 3, 0, 8, 7, 8, 7, 2, 3, 1, 0, 2, 6])
unique, unique_counts = np.unique(arr, return_counts=True)

for i, j in zip(unique, unique_counts):
  print(i, j)

0 2
1 3
2 3
3 3
6 1
7 2
8 2


In [ ]:
#Multiply matrices of complex numbers using NumPy in Python
arr_1 = np.array([1+4j, 3+9j])  
arr_2 = np.array([2+2j, 10+1j])
  
print(np.vdot(arr_1, arr_2))

(49-93j)


In [ ]:
#Compute the outer product of two given vectors using NumPy in Python
arr_1 = np.array([1, 2])
arr_2 = np.array([3, 4])

print(np.outer(arr_1, arr_2))

[[3 4]
 [6 8]]


In [ ]:
#Calculate inner, outer, and cross products of matrices and vectors using NumPy
arr_1 = np.array([[5, 3], [9, 7]])  
arr_2 = np.array([[2, 10], [4, 3]])
  
#inner product
print(np.inner(arr_1, arr_2))

#outer product
print(np.outer(arr_1, arr_2))

#cross product 
print(np.cross(arr_1, arr_2))

[[40 29]
 [88 57]]
[[10 50 20 15]
 [ 6 30 12  9]
 [18 90 36 27]
 [14 70 28 21]]
[44 -1]


In [ ]:
#Compute the covariance matrix of two given NumPy arrays
arr_1 = np.array([[5, 3], [9, 7]])  
arr_2 = np.array([[2, 10], [4, 3]])
  
print(np.cov(arr_1, arr_2))

[[ 2.   2.  -8.   1. ]
 [ 2.   2.  -8.   1. ]
 [-8.  -8.  32.  -4. ]
 [ 1.   1.  -4.   0.5]]


In [ ]:
#Convert covariance matrix to correlation matrix using Python
#fazer

In [ ]:
#Compute the Kronecker product of two mulitdimension NumPy arrays
arr_1 = np.array([[5, 3], [9, 7]])  
arr_2 = np.array([[2, 10], [4, 3]])
  
print(np.kron(arr_1, arr_2))

[[10 50  6 30]
 [20 15 12  9]
 [18 90 14 70]
 [36 27 28 21]]


In [ ]:
#Convert the matrix into a list
arr = np.array([[5, 3], [9, 7]])  
print(arr)

arr = arr.tolist()
print(arr)

[[5 3]
 [9 7]]
[[5, 3], [9, 7]]


In [ ]:
#Replace NumPy array elements that doesn’t satisfy the given condition
arr = np.array([[5, 3], [9, 7]])  
print(arr)

print(np.where(arr > 6, 6, arr)) # replacing elements bigger than 6 per 6

[[5 3]
 [9 7]]
[[5 3]
 [6 6]]


In [ ]:
#Return the indices of elements where the given condition is satisfied
#Using the same method as the question above
arr = np.array([[5, 3], [9, 7]])  
print(arr)

print(np.where(arr > 6)) # showing all elements that match the condition

[[5 3]
 [9 7]]
(array([1, 1]), array([0, 1]))


In [ ]:
#Replace NaN values with average of columns
arr = np.array([[np.nan, 3], [9, np.nan], [10, 28]])  
print(arr)

nan_indices = np.where(np.isnan(arr))
columns_mean = np.nanmean(arr, axis=0)
arr[nan_indices] = np.take(columns_mean, nan_indices[1])

print(arr)

[[nan  3.]
 [ 9. nan]
 [10. 28.]]
[[ 9.5  3. ]
 [ 9.  15.5]
 [10.  28. ]]


In [ ]:
#Replace negative value with zero in numpy array
arr = np.array([[-5, 3], [9, -7]])  
print(arr)

print(np.where(arr < 0, 0, arr)) # replacing negative elements per 0

[[-5  3]
 [ 9 -7]]
[[0 3]
 [9 0]]


In [ ]:
#How to get values of an NumPy array at certain index positions?
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6, 7])

print(arr_1)
arr_1.put([0, 2], arr_2)
print(arr_1)

[1 2 3]
[4 2 5]


In [ ]:
#Find indices of elements equal to zero in a NumPy array
arr = np.array([[5, 0], [9, 0]])  
print(arr)

print(np.where(arr == 0)) # showing all elements that match the condition

[[5 0]
 [9 0]]
(array([0, 1]), array([1, 1]))


In [ ]:
#How to Remove columns in Numpy array that contains non-numeric values?
arr = np.array([[1, np.nan, 3], [4, np.nan, np.nan], [7, 8, 9]])
print(arr)
  
arr = arr[:, ~np.isnan(arr).any(axis=0)]# removing columns with nan values 
print(arr)

[[ 1. nan  3.]
 [ 4. nan nan]
 [ 7.  8.  9.]]
[[1.]
 [4.]
 [7.]]


In [ ]:
#How to access different rows of a multidimensional NumPy array?
arr = np.array([[1, np.nan, 3], [4, np.nan, np.nan], [7, 8, 9]])
print(arr)

print(arr[[1, 2]]) # accessing row 1 and 2

[[ 1. nan  3.]
 [ 4. nan nan]
 [ 7.  8.  9.]]
[[ 4. nan nan]
 [ 7.  8.  9.]]


In [ ]:
#Get row numbers of NumPy array having element larger than X
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

print(np.where(np.any(arr > 3, axis=1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 2]),)


In [ ]:
#Get filled the diagonals of NumPy array
arr = np.array([[1, 2], [3, 4]])
print(arr)

np.fill_diagonal(arr, 3)
print(arr)

[[1 2]
 [3 4]]
[[3 2]
 [3 3]]


In [ ]:
#Check elements present in the NumPy array
arr = np.array([1, 2, 3, 4, 5])
elements = np.array([9, 3, 1, 5, 0, 10])

print(np.isin(arr, elements))

[ True False  True False  True]


In [ ]:
#Combined array index by index
arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr = arr[np.array([2, 2, 1, 0, 3, 3])]
print(arr)

[1 2 3 4 5]
[3 3 2 1 4 4]


In [ ]:
#Find a matrix or vector norm using NumPy
arr = np.arange(5)
print(arr)

print(np.linalg.norm(arr))

[0 1 2 3 4]
5.477225575051661


In [ ]:
#Calculate the QR decomposition of a given matrix using NumPy
arr = np.arange(9).reshape(3, 3)
print(arr)

Q, R = np.linalg.qr(arr)

print("MATRIX Q:")
print(Q)

print("MATRIX R:")
print(R)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
MATRIX Q:
[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]
MATRIX R:
[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.75770186e-15]]


In [ ]:
#Compute the condition number of a given matrix using NumPy
arr = np.arange(9).reshape(3, 3)
print(arr)

print(np.linalg.cond(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2.857326358417597e+16


In [ ]:
#Compute the eigenvalues and right eigenvectors of a given square array using NumPy?
arr = np.array([[1, 2], [3, 4]])

eigen_values, eigen_vectors = np.linalg.eig(arr)

print("Eigenvalues:")
print(eigen_values)

print("Eigenvectors:")
print(eigen_vectors)


Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#Calculate the Euclidean distance using NumPy
arr_1 = np.array((1, 1, 1))
arr_2 = np.array((8, 4, 2))
  
print(np.linalg.norm(arr_1 - arr_2))

7.681145747868608


In [13]:
#Create a Numpy array with random values
arr = np.empty([3])
print(arr)

[1.5e-323 9.9e-324 1.5e-323]


In [6]:
#How to choose elements from the list with different probability using NumPy?
arr = [1, 2, 3]
random_elements = np.random.choice(arr, 3, p=[0.2, 0.4, 0.4]) #using weights to get different probability for the elements
print(random_elements)

[3 2 3]


In [8]:
#How to get weighted random choice in Python?
arr = [1, 2, 3]
random_elements = np.random.choice(arr, 3, p=[0.2, 0.4, 0.4])
print(random_elements)

[2 2 3]


In [18]:
#Generate Random Numbers From The Uniform Distribution using NumPy
arr = np.random.uniform(size=9)
print(arr)

[[0.08302057 0.33997567 0.56245427]
 [0.16623641 0.5798786  0.49332899]
 [0.15817274 0.56374367 0.68886444]]


In [11]:
#Get Random Elements form geometric distribution
arr = np.random.geometric(0.4, size=9)
print(arr)

[3 4 4 1 2 5 2 1 5]


In [12]:
#Get Random elements from Laplace distribution
arr = np.random.laplace(size=9)
print(arr)

[-0.79552275 -3.9455366   0.13388805 -0.7773208  -0.55997533  0.18159928
  1.48600678  1.81289792 -0.92574282]


In [19]:
#Return a Matrix of random values from a uniform distribution
arr = np.random.uniform(size=(3, 4))
print(arr)

[[0.61146543 0.85740707 0.53938634 0.24400217]
 [0.28263958 0.44472862 0.26666387 0.20077295]
 [0.15893697 0.88091152 0.80495538 0.71750016]]


In [20]:
#Return a Matrix of random values from a Gaussian distribution
arr = np.random.normal(size=(3, 4))
print(arr)

[[-1.04504656  0.5350823   0.71382957  1.2596136 ]
 [ 0.41270976 -0.02757823  0.82276138  0.29014767]
 [ 0.21492593  1.1656507   0.58168732 -0.66140308]]


In [23]:
#How to get the indices of the sorted array using NumPy in Python?
arr = np.array([1, 2, 5, 4, 3])
indices = np.argsort(arr)
print(indices)

[0 1 4 3 2]


In [28]:
#Finding the k smallest values of a NumPy array
arr = np.array([1, 9, 21, 3, 1, 2, 0, 7, 5, 23, 9])
k = 4

arr = np.sort(arr)
print(arr[:k])

[0 1 1 2]


In [31]:
#How to get the n-largest values of an array using NumPy?
arr = np.array([1, 9, 21, 3, 1, 2, 0, 7, 5, 23, 9])
k = 4

arr = np.sort(arr)
print(arr[-k:])

[ 9  9 21 23]


In [39]:
#Sort the values in a matrix
arr = np.array([1, 3, 2, 5, 5, 4, 8, 7, 9]).reshape(3, 3)
print(arr)

arr.sort()
print(arr)

[[1 3 2]
 [5 5 4]
 [8 7 9]]
[[1 2 3]
 [4 5 5]
 [7 8 9]]


In [40]:
#Filter out integers from float numpy array
arr = np.array([1.0, 1.1, 1.2, 1.4, 9.0, 3.0, 0.2, 0.0, -1.0])
arr = arr[arr != arr.astype(int)]
print(arr)

[1.1 1.2 1.4 0.2]


In [41]:
#Find the indices into a sorted array
arr = np.array([1, 2, 5, 4, 3]) # I thought that this question was similar to one that I already answered, so I just repeated the code
indices = np.argsort(arr)
print(indices)

[0 1 4 3 2]


In [43]:
#How to get element-wise true division of an array using Numpy?
arr = np.arange(9)
print(arr)

print(np.true_divide(arr, 2))

[0 1 2 3 4 5 6 7 8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [44]:
#How to calculate the element-wise absolute value of NumPy array?
arr = np.array([1, -1, 2, -3, -5, 4, 0, -10, 2])
print(arr)

print(np.absolute(arr))

[  1  -1   2  -3  -5   4   0 -10   2]
[ 1  1  2  3  5  4  0 10  2]


In [48]:
#Compute the negative of the NumPy array
arr = np.array([1, -1, 2, -3, -5, 4, 0, -10, 2])
print(arr)

print(np.negative(arr))

[  1  -1   2  -3  -5   4   0 -10   2]
[-1  1 -2  3  5 -4  0 10 -2]


In [49]:
#Multiply 2d numpy array corresponding to 1d array
arr_1 = np.array([1, -1, 2, -3, -5, 4, 0, -10, 2]).reshape(3, 3)
arr_2 = np.array([0, 2, 3])
print(arr_1)

print(arr_1 * arr_2[:, np.newaxis])

[[  1  -1   2]
 [ -3  -5   4]
 [  0 -10   2]]
[[  0   0   0]
 [ -6 -10   8]
 [  0 -30   6]]


In [50]:
#Computes the inner product of two arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(np.inner(arr_1, arr_2))

32


In [54]:
#Compute the nth percentile of the NumPy array
arr = np.array([1, 2, 3])
print(np.percentile(arr, 25))

1.5


In [57]:
#Calculate the n-th order discrete difference along the given axis
arr = np.array([1, 2, 3, 8, 1, 0, 2])
print(np.diff(arr))

[ 1  1  5 -7 -1  2]


In [58]:
#Calculate the sum of all columns in a 2D NumPy array
arr = np.arange(9).reshape(3, 3)
print(arr)
print(np.sum(arr, axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [59]:
#Calculate average values of two given NumPy arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print((arr_1 + arr_2) / 2)

[2.5 3.5 4.5]


In [ ]:
#How to compute numerical negative value for all elements in a given NumPy array?
arr = np.array([1, -1, 2, -3, -5, 4, 0, -10, 2]) # similar to a question already answered
print(arr)

print(np.negative(arr))

In [60]:
#How to get the floor, ceiling and truncated values of the elements of a numpy array?
arr = np.array([1.0, 2.2, -9.3, -1.5, -4.0, 3.7])
print(arr)

print(np.floor(arr)) # floor

print(np.ceil(arr)) # ceil

print(np.trunc(arr)) # trunc
  

[ 1.   2.2 -9.3 -1.5 -4.   3.7]
[  1.   2. -10.  -2.  -4.   3.]
[ 1.  3. -9. -1. -4.  4.]
[ 1.  2. -9. -1. -4.  3.]


In [61]:
#How to round elements of the NumPy array to the nearest integer?
arr = np.array([1.0, 2.2, -9.3, -1.5, -4.0, 3.7])
print(arr)

print(np.rint(arr))

[ 1.   2.2 -9.3 -1.5 -4.   3.7]
[ 1.  2. -9. -2. -4.  4.]


In [62]:
#Find the round off the values of the given matrix
arr = np.array([[1.2, 1.0, 3.2, -1.1], [-2.9, 1.9, 1.4, 3.0]])
print(arr.round())

[[ 1.  1.  3. -1.]
 [-3.  2.  1.  3.]]


In [64]:
#Determine the positive square-root of an array
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [68]:
#Evaluate Einstein’s summation convention of two multidimensional NumPy arrays
arr_1 = np.array([1, 2])
arr_2 = np.array([3, 4])
print(np.einsum("n, n", arr_1, arr_2))

11


In [74]:
#Compute the median of the flattened NumPy array
arr = np.array([1, 4, 2, 6, 7, 4, 2, 1, 90])
print(np.median(arr))

4.0
