In [77]:
import numpy as np

In [28]:
#How to create an empty and a full NumPy array?
empty_arr = np.array([])
full_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(empty_arr)
print(full_arr)

[]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#Create a Numpy array filled with all zeros
arr = np.zeros([3, 3], dtype = int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
#Create a Numpy array filled with all ones
arr = np.ones([3, 3], dtype = int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [32]:
#Check whether a Numpy array contains a specified row
arr = np.ones([3, 3], dtype = int) # 3x3 array filled with ones 
row_1 = [1, 1, 1]
row_2 = [1, 1, 0]

print(arr)
print(row_1 in arr.tolist())
print(row_2 in arr.tolist())

[[1 1 1]
 [1 1 1]
 [1 1 1]]
True
False


In [36]:
#How to Remove rows in Numpy array that contains non-numeric values?
arr = np.array([[1, np.nan, 3], [4, np.nan, np.nan], [7, 8, 9]])
print(arr)
  
arr = arr[~np.isnan(arr).any(axis=1)]# removing rows with nan values 
print(arr)

[[ 1. nan  3.]
 [ 4. nan nan]
 [ 7.  8.  9.]]
[[7. 8. 9.]]


In [43]:
#Remove single-dimensional entries from the shape of an array
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr.shape)
arr = arr.squeeze()
print(arr.shape)

(1, 2, 3)
(2, 3)


In [54]:
#Find the number of occurrences of a sequence in a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 3, 2], [3, 1, 2]])
print(arr)
sequence = "1, 2"
print(repr(arr).count(sequence))

[[1 2 3]
 [4 5 6]
 [1 3 2]
 [3 1 2]]
2


In [68]:
#Find the most frequent value in a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 1, 3, 2, 3, 1, 2])
print(arr)

element_count = np.bincount(arr)
index = 0

while index < len(element_count):
    if element_count[index] == max(element_count):
      print(index, end=" ")

    index += 1

[1 2 3 4 5 6 1 3 2 3 1 2]
1 2 3 

In [70]:
#Combining a one and a two-dimensional NumPy Array
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

for (i, j) in np.nditer([arr_1d, arr_2d]):
  print(i, j)

1 4
2 5
3 6
1 7
2 8
3 9


In [87]:
#How to build an array of all combinations of two NumPy arrays?
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(np.array(np.meshgrid(arr_1, arr_2)).T.reshape(-1, 2))

[[1 4]
 [1 5]
 [1 6]
 [2 4]
 [2 5]
 [2 6]
 [3 4]
 [3 5]
 [3 6]]


In [90]:
#How to add a border around a NumPy array?
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
  
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=-1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[-1 -1 -1 -1 -1]
 [-1  1  2  3 -1]
 [-1  4  5  6 -1]
 [-1 -1 -1 -1 -1]]


In [94]:
#How to compare two NumPy arrays?
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

comparison = (arr_1 == arr_2)

if comparison.all():
  print('Iguais')
else:
  print('Diferentes')

Diferentes


In [96]:
#How to check whether specified values are present in NumPy array?
arr = np.array([1, 2, 3])

print(1 in arr)
print(4 in arr)

True
False


In [108]:
#How to get all 2D diagonals of a 3D NumPy array?
arr = np.arange(3 * 3 * 3).reshape(3, 3, 3)
print(arr)  
print('--------------------------------------')

diagonals = np.diagonal(arr)
print(diagonals)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------------------------
[[ 0 12 24]
 [ 1 13 25]
 [ 2 14 26]]


In [110]:
#Flatten a Matrix in Python using NumPy
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [111]:
#Flatten a 2d numpy array into 1d array
# basically the same thing that the question above does, so I just repeated the flatten() method
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [130]:
#Move axes of an array to new positions
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr.shape)

arr = np.moveaxis(arr, 0, 1)
print(arr.shape)

(2, 3)
(3, 2)


In [132]:
#Interchange two axes of an array
#Pretty much the same thing, but the method swapaxes swap two axes while moveaxis can move the position of more than 2 axes
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr.shape)

arr = np.swapaxes(arr, 0, 1)
print(arr.shape)

(2, 3)
(3, 2)


In [145]:
#NumPy – Fibonacci Series using Binet Formula
n = int(input("Enter the value of n: "))
fibonacci_numbers = np.arange(0, n)

alpha = (1 + np.sqrt(5)) / 2
beta = (1 - np.sqrt(5)) / 2
fn = ((alpha ** fibonacci_numbers) - (beta ** fibonacci_numbers)) * (1 / np.sqrt(5))

print("These are the numbers of the first n fibonacci series:")
print(fn)

Enter the value of n: 10
These are the numbers of the first n fibonacci series:
[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]


In [146]:
#Counts the number of non-zero values in the array
arr = np.array([1, 2, 3, 0, 1, 2, 0, 3, 40, 0, 2])
print(np.count_nonzero(arr))

8


In [147]:
#Count the number of elements along a given axis
arr = np.array([[1, 2, 3], [4, 5, 6]]) 

print(np.size(arr, 0)) # x-axis
print(np.size(arr, 1)) # y-axis

2
3


In [151]:
#Trim the leading and/or trailing zeros from a 1-D array
arr = np.array([0, 0, 1, 2, 3, 0, 1, 2, 0, 3, 40, 0, 2, 0])
print(arr)

arr = np.trim_zeros(arr)
print(arr)

[ 0  0  1  2  3  0  1  2  0  3 40  0  2  0]
[ 1  2  3  0  1  2  0  3 40  0  2]


In [156]:
#Change data type of given numpy array
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = arr.astype('bool')
print(arr.dtype)

int64
bool
[ True  True  True]


In [158]:
#Reverse a numpy array
arr = np.array([1, 2, 3])
print(arr)

arr = np.flipud(arr)
print(arr)

[1 2 3]
[3 2 1]


In [161]:
#How to make a NumPy array read-only?
arr = np.array([1, 2, 3])
print(arr)

arr[0] = 10
print(arr)

arr.flags.writeable = False
#arr[0] = 2 #uncomment to see the error

[1 2 3]
[10  2  3]


In [165]:
#Get the maximum value from given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.max(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
9


In [166]:
#Get the minimum value from given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.min(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
0


In [167]:
#Find the number of rows and columns of a given matrix using NumPy
arr = np.arange(10).reshape(2, 5)
print(arr.shape)

(2, 5)


In [169]:
#Select the elements from a given matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(arr[0][2])
print(arr[1][1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
6


In [170]:
#Find the sum of values in a matrix
arr = np.arange(10).reshape(2, 5)
print(arr)
print(np.sum(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45
